global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'app_printing'
    static_configs:
      - targets: ['158.160.14.173:81']
    # metrics_path: /metrics/delivery
  - job_name: 'app_delivery'
    static_configs:
      - targets: ['158.160.14.173:80']
  - job_name: 'app_cart'
    static_configs:
      - targets: ['158.160.14.173:86']