name: CI/CD Pipeline

on:
  push:
    branches:
      - vm

jobs:

  update-and-deploy:
    runs-on: ubuntu-latest
    needs: [ test-app-printing, test-app-cart, test-app-promocode, test-app-item, test-app-order, test-app-payment, test-app-delivery ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH into VM and Update Repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ./MA_Clothes_Delivery_Project
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S git pull

      - name: Recreate Docker Containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ./MA_Clothes_Delivery_Project
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose up --build -d
